// CSV = Cosmic Survey Vessel. ASCII callsigns fit the arcade font;
// full names retain their spelling in the fleet record and documentation.
export const fleetPhysicists=[
 ["Archimedes", "CSV ARCHIMEDES"],
 ["Ibn al-Haytham", "CSV ALHAZEN"],
 ["Galileo Galilei", "CSV GALILEO"],
 ["Johannes Kepler", "CSV KEPLER"],
 ["Isaac Newton", "CSV NEWTON"],
 ["Christiaan Huygens", "CSV HUYGENS"],
 ["Robert Hooke", "CSV HOOKE"],
 ["Daniel Bernoulli", "CSV BERNOULLI"],
 ["Charles-Augustin de Coulomb", "CSV COULOMB"],
 ["Alessandro Volta", "CSV VOLTA"],
 ["André-Marie Ampère", "CSV AMPERE"],
 ["Michael Faraday", "CSV FARADAY"],
 ["James Prescott Joule", "CSV JOULE"],
 ["James Clerk Maxwell", "CSV MAXWELL"],
 ["Ludwig Boltzmann", "CSV BOLTZMANN"],
 ["Josiah Willard Gibbs", "CSV GIBBS"],
 ["Max Planck", "CSV PLANCK"],
 ["Marie Curie", "CSV M. CURIE"],
 ["Pierre Curie", "CSV P. CURIE"],
 ["Henri Becquerel", "CSV BECQUEREL"],
 ["Ernest Rutherford", "CSV RUTHERFORD"],
 ["Albert Einstein", "CSV EINSTEIN"],
 ["Niels Bohr", "CSV BOHR"],
 ["Emmy Noether", "CSV NOETHER"],
 ["Lise Meitner", "CSV MEITNER"],
 ["Satyendra Nath Bose", "CSV BOSE"],
 ["C. V. Raman", "CSV RAMAN"],
 ["Louis de Broglie", "CSV DE BROGLIE"],
 ["Erwin Schrödinger", "CSV SCHRODINGER"],
 ["Werner Heisenberg", "CSV HEISENBERG"],
 ["Wolfgang Pauli", "CSV PAULI"],
 ["Paul Dirac", "CSV DIRAC"],
 ["Enrico Fermi", "CSV FERMI"],
 ["Chien-Shiung Wu", "CSV WU"],
 ["Maria Goeppert Mayer", "CSV MAYER"],
 ["J. Robert Oppenheimer", "CSV OPPENHEIMER"],
 ["Richard Feynman", "CSV FEYNMAN"],
 ["Julian Schwinger", "CSV SCHWINGER"],
 ["Sin-Itiro Tomonaga", "CSV TOMONAGA"],
 ["Abdus Salam", "CSV SALAM"],
 ["Chen Ning Yang", "CSV YANG"],
 ["Tsung-Dao Lee", "CSV LEE"],
 ["Vera Rubin", "CSV RUBIN"],
 ["Cecilia Payne-Gaposchkin", "CSV PAYNE"],
 ["Subrahmanyan Chandrasekhar", "CSV CHANDRASEKHAR"],
 ["John Archibald Wheeler", "CSV WHEELER"],
 ["Steven Weinberg", "CSV WEINBERG"],
 ["Stephen Hawking", "CSV HAWKING"],
 ].map(([name,ship])=>({name,ship}));
