// USS honors U.S. teaching/research affiliations, including visiting posts.
// Other honorees use STARSHIP. ASCII callsigns fit the arcade font;
// full names retain their spelling in the fleet record and documentation.
export const fleetPhysicists=[
 ["Archimedes", "STARSHIP ARCHIMEDES"],
 ["Ibn al-Haytham", "STARSHIP ALHAZEN"],
 ["Galileo Galilei", "STARSHIP GALILEO"],
 ["Johannes Kepler", "STARSHIP KEPLER"],
 ["Isaac Newton", "STARSHIP NEWTON"],
 ["Christiaan Huygens", "STARSHIP HUYGENS"],
 ["Robert Hooke", "STARSHIP HOOKE"],
 ["Daniel Bernoulli", "STARSHIP BERNOULLI"],
 ["Charles-Augustin de Coulomb", "STARSHIP COULOMB"],
 ["Alessandro Volta", "STARSHIP VOLTA"],
 ["André-Marie Ampère", "STARSHIP AMPERE"],
 ["Michael Faraday", "STARSHIP FARADAY"],
 ["James Prescott Joule", "STARSHIP JOULE"],
 ["James Clerk Maxwell", "STARSHIP MAXWELL"],
 ["Ludwig Boltzmann", "USS BOLTZMANN"],
 ["Josiah Willard Gibbs", "USS GIBBS"],
 ["Max Planck", "STARSHIP PLANCK"],
 ["Marie Curie", "STARSHIP M. CURIE"],
 ["Pierre Curie", "STARSHIP P. CURIE"],
 ["Henri Becquerel", "STARSHIP BECQUEREL"],
 ["Ernest Rutherford", "STARSHIP RUTHERFORD"],
 ["Albert Einstein", "USS EINSTEIN"],
 ["Niels Bohr", "USS BOHR"],
 ["Emmy Noether", "USS NOETHER"],
 ["Lise Meitner", "USS MEITNER"],
 ["Satyendra Nath Bose", "STARSHIP BOSE"],
 ["C. V. Raman", "STARSHIP RAMAN"],
 ["Louis de Broglie", "STARSHIP DE BROGLIE"],
 ["Erwin Schrödinger", "STARSHIP SCHRODINGER"],
 ["Werner Heisenberg", "USS HEISENBERG"],
 ["Wolfgang Pauli", "USS PAULI"],
 ["Paul Dirac", "USS DIRAC"],
 ["Enrico Fermi", "USS FERMI"],
 ["Chien-Shiung Wu", "USS WU"],
 ["Maria Goeppert Mayer", "USS MAYER"],
 ["J. Robert Oppenheimer", "USS OPPENHEIMER"],
 ["Richard Feynman", "USS FEYNMAN"],
 ["Julian Schwinger", "USS SCHWINGER"],
 ["Sin-Itiro Tomonaga", "USS TOMONAGA"],
 ["Abdus Salam", "USS SALAM"],
 ["Chen Ning Yang", "USS YANG"],
 ["Tsung-Dao Lee", "USS LEE"],
 ["Vera Rubin", "USS RUBIN"],
 ["Cecilia Payne-Gaposchkin", "USS PAYNE"],
 ["Subrahmanyan Chandrasekhar", "USS CHANDRASEKHAR"],
 ["John Archibald Wheeler", "USS WHEELER"],
 ["Steven Weinberg", "USS WEINBERG"],
 ["Stephen Hawking", "USS HAWKING"],
 ].map(([name,ship])=>({name,ship}));
