const assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const engine=process.argv[2]||'chromium';
(async()=>{let b,p;const errors=[];try{
 b=await (engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true,env:{...process.env,PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS:'1',LIBGL_ALWAYS_SOFTWARE:'1'}}:{executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
 const context=await b.newContext({viewport:{width:390,height:844},hasTouch:true,deviceScaleFactor:2});p=await context.newPage();p.setDefaultTimeout(30000);
 p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/CONTEXT_LOST_WEBGL/.test(m.text()))errors.push(m.text())});
 await p.addInitScript(()=>{
  const original=WebGL2RenderingContext.prototype.drawArrays;
  WebGL2RenderingContext.prototype.drawArrays=function(...args){original.apply(this,args);{const data=new Uint8Array(this.drawingBufferWidth*this.drawingBufferHeight*4);this.readPixels(0,0,this.drawingBufferWidth,this.drawingBufferHeight,this.RGBA,this.UNSIGNED_BYTE,data);let lit=0;for(let i=0;i<data.length;i+=4)if(Math.max(data[i],data[i+1],data[i+2])>45)lit++;window.__framePixels=Array.from(data);window.__pixels={lit,total:data.length/4,error:this.getError()}}};
 });
 await p.route('**/game.js?*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+`
flightProgram.nextOffer=()=>null;const lossExtension=gl.getExtension('WEBGL_lose_context'),soundCalls={laser:0,explosion:0};for(const kind of ['laser','explosion']){const original=score[kind].bind(score);score[kind]=()=>{soundCalls[kind]++;original()}}window.__qa={audioAttach(){this.analyser=score.context.createAnalyser();this.analyser.fftSize=2048;score.effects.connect(this.analyser)},audioRms(){const data=new Float32Array(2048);this.analyser.getFloatTimeDomainData(data);return Math.sqrt(data.reduce((sum,x)=>sum+x*x,0)/data.length)},soundCalls,async audioSample(kind){const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext,s=new ArcadeScore();s.context=new Offline(1,52800,48000);s.effects=s.context.destination;s.noise=score.noise;s.playing=true;s[kind]();const data=(await s.context.startRendering()).getChannelData(0),rms=(a,b)=>Math.sqrt(data.slice(a,b).reduce((sum,x)=>sum+x*x,0)/(b-a));return {head:rms(0,4800),tail:rms(48000,52800),body:rms(24000,28800)}},audioState(){return {state:score.context.state,level:score.thrustLevel}},prepareTarget(){reset();trafficFire.enabled=false;const rho=.35,s=fleet[0];s.id='QA TARGET';s.A=add(player.X,player.F,Math.cosh(rho),Math.sinh(rho));s.B=player.U.slice();s.C=[player.R.slice(),player.V.slice(),add(player.F,player.X,Math.cosh(rho),Math.sinh(rho))];s.kind=0;s.size=1.5;s.boundRadius=.065;warp=10;$('warp').value='10';dirty=true;return s.id},laser(){const b=beams.at(-1),phase=b?player.t-b.t:0,X=b&&laserEvent(b,phase),v=X&&dot(X,viewObserver().F);return {visible:!!b&&!b.impact&&v>.001,phase,flashExpired:!!b&&effectTime-b.flashTime>.24}},prepareReturn(){reset();trafficFire.enabled=false;const b=createLaser(player,[]);b.flashTime=effectTime;beams=[b];shots=1;while(player.t<3.04)advance(player,.004,0,false,(seg,t)=>advanceLasers(beams,t,seg));warp=10;dirty=true},age(){const s=fleet.find(s=>s.explosionStarted!==undefined&&!s.visualRemoved);return s?effectTime-s.explosionStarted:-1},effects(){const data=hctx.getImageData(0,0,hud.width,hud.height).data;let redPixels=0;for(let i=0;i<data.length;i+=4)if(data[i]>100&&data[i]>data[i+1]*1.15&&data[i+3]>15)redPixels++;return {effectTime,explosions:fleet.filter(s=>s.explosionStarted!==undefined&&!s.visualRemoved).map(s=>({id:s.id,age:effectTime-s.explosionStarted})),redPixels}},frame(){return snapshot(player)},loseContext(){lossExtension.loseContext()},restoreContext(){lossExtension.restoreContext()}};
`})});
 await p.goto(process.env.ADS_URL || 'http://127.0.0.1:8080/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.adsFlight?.getState().renderer.frames>0);console.log(JSON.stringify({engine,stage:'render',pixels:await p.evaluate(()=>window.__pixels),state:await p.evaluate(()=>window.adsFlight.getState())}));
 const pixels=await p.evaluate(()=>window.__pixels);assert.ok(pixels.lit>250);assert.equal(pixels.error,0);
 assert.ok(await p.locator('.touch-controls').isVisible());assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.keyboard.press('ArrowLeft');assert.equal((await p.evaluate(()=>window.adsFlight.getState())).pilot,'Edward Witten');await p.keyboard.press('ArrowRight');assert.equal((await p.evaluate(()=>window.adsFlight.getState())).pilot,'Juan Maldacena');await p.locator('#launchButton').click({force:true});assert.equal((await p.evaluate(()=>window.adsFlight.getState())).storyVisible,true);const frozen=(await p.evaluate(()=>window.adsFlight.getState())).properTime;await p.waitForTimeout(150);assert.equal((await p.evaluate(()=>window.adsFlight.getState())).properTime,frozen);for(let i=0;i<10&&(await p.evaluate(()=>window.adsFlight.getState().storyVisible));i++)await p.locator('#introContinue').click();await p.waitForFunction(()=>window.adsFlight.getState().properTime>0);
 await p.keyboard.press('m');assert.equal(await p.locator('#flightMap').isVisible(),true);assert.equal(await p.locator('#mapOverlayButton').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#mapDialog').evaluate(d=>d.open),false);
 const mapTime=(await p.evaluate(()=>window.adsFlight.getState())).properTime;await p.waitForFunction(t=>window.adsFlight.getState().properTime>t,mapTime);
 await p.keyboard.down('w');await p.waitForFunction(()=>window.adsFlight.getState().engine.level>.4);await p.keyboard.up('w');
 assert.equal(await p.locator('#flightMapCanvas').evaluate(c=>{const r=c.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2).id}),'space');
 await p.screenshot({path:'/tmp/ads-map-overlay-'+engine+'.png'});await p.keyboard.press('m');assert.equal(await p.locator('#flightMap').isVisible(),false);
 const mapShots=(await p.evaluate(()=>window.adsFlight.getState())).shots;await p.locator('#mapOverlayButton').tap();assert.equal(await p.locator('#flightMap').isVisible(),true);assert.equal((await p.evaluate(()=>window.adsFlight.getState())).shots,mapShots);await p.keyboard.press('Escape');assert.equal(await p.locator('#flightMap').isVisible(),false);
 await p.locator('#expandMapButton').click();assert.equal(await p.locator('#mapDialog').evaluate(d=>d.open),true);assert.ok((await p.locator('#expandedMap').boundingBox()).width>(await p.locator('#map').boundingBox()).width);await p.keyboard.press('m');assert.equal(await p.locator('#mapDialog').evaluate(d=>d.open),false);
 for(const name of ['KeyW','KeyS','KeyQ','KeyE','Space','KeyF','ArrowUp','ArrowDown','ArrowLeft','ArrowRight']){const box=await p.locator('[data-key="'+name+'"]').boundingBox();assert.ok(box.width>=44&&box.height>=44,name+' has a small tap target')}
 assert.equal(await p.locator('.speed-readout .label').innerText(),'GLOBAL VELOCITY');
 await p.waitForFunction(()=>window.adsFlight.getState().music);await p.evaluate(()=>window.__qa.audioAttach());
 await p.evaluate(()=>window.adsFlight.setPause(true));
 const paints=[];let previous=await p.evaluate(()=>window.__framePixels);
 for(let i=0;i<5;i++){
  const before=(await p.evaluate(()=>window.adsFlight.getState())).renderer.frames;await p.evaluate(i=>window.adsFlight.selectPilot(i),i);await p.waitForFunction(n=>window.adsFlight.getState().renderer.frames>n,before);
  const pixels=await p.evaluate(()=>window.__framePixels);if(i)assert.ok(pixels.reduce((sum,x,j)=>sum+Math.abs(x-previous[j]),0)>1000,'Pilot must change rendered hull color');previous=pixels;paints.push((await p.evaluate(()=>window.adsFlight.getState())).shipColor);
 }
 assert.equal(new Set(paints).size,5);await p.evaluate(()=>window.adsFlight.selectPilot(0));await p.evaluate(()=>window.adsFlight.setPause(false));
 const thrust=p.locator('[data-key="KeyW"]');await thrust.scrollIntoViewIfNeeded();const box=await thrust.boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.waitForFunction(()=>window.adsFlight.getState().activeControls.includes('KeyW'));
 await p.waitForFunction(()=>window.adsFlight.getState().engine.level>.4);await p.waitForTimeout(150);
 const burn=await p.evaluate(()=>({rms:window.__qa.audioRms(),pixels:window.__qa.effects().redPixels,engine:window.adsFlight.getState().engine}));assert.ok(burn.rms>.01,'Thrust must produce audible samples');assert.ok(burn.pixels>100,'Burn plume must be visible');await p.screenshot({path:'/tmp/ads-'+engine+'-burn.png',timeout:45000});
 await p.mouse.up();await p.waitForTimeout(350);assert.equal((await p.evaluate(()=>window.adsFlight.getState())).engine.soundLevel,0);assert.ok(await p.evaluate(()=>window.__qa.audioRms())<.002,'Engine must stop after release');
 const calls=await p.evaluate(()=>window.__qa.soundCalls.laser);await p.locator('#touchFire').tap();assert.ok(await p.evaluate(()=>window.__qa.soundCalls.laser)>calls,'Firing must trigger the laser sound');
 const sounds=await p.evaluate(async()=>({laser:await window.__qa.audioSample('laser'),explosion:await window.__qa.audioSample('explosion')}));for(const kind of ['laser','explosion']){assert.ok(sounds[kind].head>.01,kind+' must produce audible samples');assert.ok(sounds[kind].tail<.0001,kind+' must end cleanly')}assert.ok(sounds.explosion.body>.001,'Explosion must have a sustained decay');
 console.log(JSON.stringify({engine,stage:'paint-audio-burn',paints,burn,sounds}));assert.ok(!(await p.evaluate(()=>window.adsFlight.getState())).activeControls.includes('KeyW'));
 if(engine==='chromium'){
  const cdp=await context.newCDPSession(p),left=await p.locator('[data-key="ArrowLeft"]').boundingBox(),fire=await p.locator('#touchFire').boundingBox(),points=[{x:box.x+box.width/2,y:box.y+box.height/2,id:1},{x:left.x+left.width/2,y:left.y+left.height/2,id:2}];
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});await p.waitForFunction(()=>{const s=window.adsFlight.getState();return s.activeControls.includes('KeyW')&&s.activeControls.includes('ArrowLeft')});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForFunction(()=>window.adsFlight.getState().activeControls.length===0);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:fire.x+fire.width/2,y:fire.y+fire.height/2,id:3}]});await p.waitForFunction(()=>window.adsFlight.getState().shots>=2);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.waitForFunction(()=>window.adsFlight.getState().activeControls.length===0);
 }
 await p.locator('#touchPause').click();assert.equal(await p.locator('#touchPause').innerText(),'RESUME');await p.locator('#touchPause').click();
 await p.locator('#touchCamera').click();assert.equal((await p.evaluate(()=>window.adsFlight.getState())).camera,'cockpit');await p.locator('#touchCamera').click();
 await p.evaluate(()=>window.__qa.prepareTarget());await p.locator('#touchFire').tap();await p.waitForFunction(()=>{const l=window.__qa.laser();if(l.visible&&l.flashExpired&&l.phase>.05&&window.__qa.effects().redPixels>300){window.adsFlight.setPause(true);return true}return false});const laser=await p.evaluate(()=>window.__qa.effects());assert.ok(laser.redPixels>300,'Laser tracer must be clearly visible after the firing flash');await p.evaluate(()=>window.adsFlight.setPause(false));await p.waitForFunction(()=>window.adsFlight.getState().kills===1);await p.waitForFunction(()=>window.adsFlight.getState().explosions===1);assert.ok(await p.evaluate(()=>window.__qa.soundCalls.explosion)>0,'Visible impact must trigger explosion audio');
 await p.waitForFunction(()=>window.__qa.age()>.3);await p.evaluate(()=>window.adsFlight.setPause(true));const blast=await p.evaluate(()=>window.__qa.effects());assert.ok(blast.redPixels>300,'Explosion must have a large visible glow');assert.equal((await p.evaluate(()=>window.adsFlight.getState())).removedShips,0);await p.screenshot({path:'/tmp/ads-'+engine+'-explosion.png',timeout:45000});
 await p.evaluate(()=>window.adsFlight.setPause(false));await p.waitForFunction(()=>window.adsFlight.getState().removedShips===1,null,{timeout:45000});const after=await p.evaluate(()=>window.adsFlight.getState());assert.equal(after.explosions,0);assert.equal(after.renderer.traffic,47);assert.equal(after.aliveShips,47);console.log(JSON.stringify({engine,stage:'combat',blast,after}));
 await p.evaluate(()=>window.__qa.prepareReturn());await p.waitForFunction(()=>window.adsFlight.getState().gameOver);const stopped=(await p.evaluate(()=>window.adsFlight.getState())).properTime;assert.equal(await p.evaluate(()=>window.adsFlight.fire()),false);await p.waitForFunction(()=>!document.getElementById('gameOverScreen').hidden);assert.equal((await p.evaluate(()=>window.adsFlight.getState())).properTime,stopped);await p.locator('#retryButton').click();assert.equal((await p.evaluate(()=>window.adsFlight.getState())).gameOver,false);
 await p.evaluate(()=>window.adsFlight.reset());assert.equal((await p.evaluate(()=>window.adsFlight.getState())).removedShips,0);
 await p.screenshot({path:'/tmp/ads-'+engine+'-mobile.png',timeout:45000});
 await p.setViewportSize({width:844,height:390});await p.waitForTimeout(100);const layout=await p.evaluate(()=>{const a=document.querySelector('#space').getBoundingClientRect(),c=document.querySelector('.touch-controls').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,overlap:a.right>c.left&&a.left<c.right&&a.bottom>c.top&&a.top<c.bottom}});assert.equal(layout.overflow,false);assert.equal(layout.overlap,false);
 await p.setViewportSize({width:1100,height:800});await p.evaluate(()=>window.adsFlight.setPause(true));const frame=(await p.evaluate(()=>window.adsFlight.getState())).renderer.frames;
 await p.evaluate(()=>window.__qa.loseContext());await p.waitForFunction(()=>!window.adsFlight.getState().renderer.ready);await p.evaluate(()=>window.__qa.restoreContext());await p.waitForFunction(()=>window.adsFlight.getState().renderer.ready&&window.adsFlight.getState().renderer.frames>0);await p.waitForTimeout(100);assert.ok((await p.evaluate(()=>window.adsFlight.getState())).renderer.frames>frame);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,engine,pixels,layout,errors}));
 }catch(e){if(p)console.log(JSON.stringify({engine,failedState:await p.evaluate(()=>window.adsFlight?.getState()).catch(()=>null),effects:await p.evaluate(()=>window.__qa?.effects()).catch(()=>null),errors}));throw e}finally{if(b)await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
