const assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const engine=process.argv[2]||'chromium';
(async()=>{const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:{headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});try{
 const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/game.js?*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+`
 flightProgram.nextOffer=()=>null;window.__controlsQa={isolate(){trafficFire.enabled=false},directions(){const o=viewObserver(),xy=local=>projectRocketPoint(o,player,local),sign=thrustForce[2]>0?1:-1,arrow=[xy([0,0,sign*.044]),xy([0,0,sign*.084])],plume=[xy([0,0,-sign*.039]),xy([0,0,-sign*.084])];return {arrow,plume,flame:hctx.getImageData(0,0,hud.width,hud.height).data.reduce((sum,v,i,a)=>i%4===0&&v>130&&v>a[i+1]*1.1&&v>a[i+2]*1.2&&a[i+3]>25?sum+1:sum,0)}},blockedFrame(){if(!pendingFence)pendingFence=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);const wait=gl.clientWaitSync,clear=hctx.clearRect,frames=renderedFrames;let clears=0;gl.clientWaitSync=()=>gl.TIMEOUT_EXPIRED;hctx.clearRect=function(...args){clears++;return clear.apply(this,args)};try{draw(false)}finally{gl.clientWaitSync=wait;hctx.clearRect=clear}return {clears,framesUnchanged:frames===renderedFrames}}};`})});
 await page.goto(process.env.ADS_URL||'http://127.0.0.1:8081/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.adsFlight?.getState().renderer.frames>0);
 assert.equal(await page.locator('[data-launch-pilot="0"] .pilot-portrait').evaluate(e=>getComputedStyle(e).backgroundSize),'150% 150%');await page.locator('.launch-pilots').screenshot({path:'/tmp/ads-v13-'+engine+'-pilots.png'});
 await page.locator('#launchSound').click();await page.locator('#launchButton').click();for(let i=0;i<10&&(await page.evaluate(()=>window.adsFlight.getState().storyVisible));i++)await page.keyboard.press('Enter');await page.evaluate(()=>window.__controlsQa.isolate());
 const checked=[];
 for(const [key,sign] of [['w',1],['s',-1]]){
  await page.evaluate(()=>{window.adsFlight.reset();window.__controlsQa.isolate()});await page.locator('#space').focus();await page.keyboard.down(key);await page.waitForFunction(sign=>window.adsFlight.getState().chaseCamera.lag*sign>.0005,sign);
  const state=await page.evaluate(()=>window.adsFlight.getState());assert.equal(state.engine.force[2],sign*1.5);assert.equal(state.engine.exhaust[2],-sign);assert.ok(state.chaseCamera.lag*sign>0);
  await page.waitForFunction(()=>window.__controlsQa.directions().flame>15);const directions=await page.evaluate(()=>window.__controlsQa.directions());const delta=pair=>pair[1].map((v,i)=>v-pair[0][i]),a=delta(directions.arrow),b=delta(directions.plume);assert.ok(a[0]*b[0]+a[1]*b[1]<0,'The displayed thrust arrow must point away from the plume');await page.screenshot({path:'/tmp/ads-v13-'+engine+'-'+key+'.png'});await page.keyboard.up(key);checked.push({key,lag:state.chaseCamera.lag,force:state.engine.force,exhaust:state.engine.exhaust,directions});
 }
 await page.keyboard.down('Space');await page.waitForFunction(()=>window.adsFlight.getState().engine.mode==='brake');const brake=await page.evaluate(()=>window.adsFlight.getState().engine);assert.ok(brake.force.reduce((sum,v,i)=>sum+v*brake.exhaust[i],0)<0);await page.keyboard.up('Space');await page.evaluate(()=>window.adsFlight.setPause(true));const blocked=await page.evaluate(()=>window.__controlsQa.blockedFrame());assert.equal(blocked.clears,0);assert.equal(blocked.framesUnchanged,true);await page.evaluate(()=>window.adsFlight.reset());assert.equal((await page.evaluate(()=>window.adsFlight.getState())).chaseCamera.lag,0);assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,engine,checked,brake:true,synchronizedFrames:blocked,portraitFraming:true,errors}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
