const assert=require('node:assert/strict');const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const engine=process.argv[2]||'chromium';
(async()=>{const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true,env:{...process.env,PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS:'1',LIBGL_ALWAYS_SOFTWARE:'1'}}:{executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});try{const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.ADS_URL||'http://127.0.0.1:8080/');await page.waitForFunction(()=>window.adsFlight?.getState().renderer.ready);assert.equal(await page.locator('#introScreen').isVisible(),false);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>window.adsFlight.getState().renderer.ready);await page.keyboard.press('Enter');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).pilot,'Steven Gubser');const expected=['2126 AD','speed compactification','selection of the restaurant','twisted graphene','Welcome to AdS!'];
 for(let i=0;i<5;i++){
  const state=await page.evaluate(()=>window.adsFlight.getState());assert.equal(state.storyParagraph,i+1);assert.equal(state.properTime,0);assert.equal(await page.locator('[data-intro-paragraph]:visible').count(),1);assert.ok((await page.locator('[data-intro-paragraph]:visible .intro-readable').textContent()).includes(expected[i]));assert.equal(await page.locator('#app').evaluate(e=>e.inert),true);assert.equal(await page.locator('#space').isVisible(),true);
  const before=await page.locator('#introScreen').boundingBox();
  if(i===0){
   await page.waitForFunction(()=>document.querySelector('.intro-caret'));
   await page.screenshot({path:'/tmp/ads-'+engine+'-briefing-typing.png'});
   await page.waitForFunction(()=>document.querySelector('#introContinue').textContent==='NEXT →');
  }else if(i<4){
   assert.equal(await page.locator('#introContinue').textContent(),'SHOW TEXT');
   const revealed=()=>page.locator('[data-intro-paragraph]:visible .intro-letter').evaluateAll(letters=>letters.filter(l=>getComputedStyle(l).visibility==='visible').length);
   const count=await revealed();await page.waitForTimeout(150);assert.ok(await revealed()>count,'Letters should appear over time');
   if(i===1)await page.locator('#introClose').click();else if(i===2)await page.keyboard.press('Enter');else await page.keyboard.press('Escape');
   assert.equal((await page.evaluate(()=>window.adsFlight.getState())).storyParagraph,i+1,'Revealing text must not skip the paragraph');
  }
  const after=await page.locator('#introScreen').boundingBox();for(const key of ['x','y','width','height'])assert.ok(Math.abs(before[key]-after[key])<.5,'Typing must not move or resize the popup');
  assert.equal(await page.locator('[data-intro-paragraph]:visible .intro-letter').evaluateAll(letters=>letters.every(l=>getComputedStyle(l).visibility==='visible')),true);
  assert.equal(await page.locator('.intro-caret').count(),0);
  const popup=await page.locator('#introScreen').boundingBox();assert.ok(popup.width<page.viewportSize().width);assert.ok(popup.height<page.viewportSize().height);const close=await page.locator('#introClose').boundingBox();assert.ok(close.width>=44&&close.height>=44);
  if(i===0){await page.screenshot({path:'/tmp/ads-'+engine+'-popup-desktop.png'});await page.mouse.click(3,3);assert.equal((await page.evaluate(()=>window.adsFlight.getState())).storyParagraph,1);await page.evaluate(()=>document.dispatchEvent(new KeyboardEvent('keydown',{code:'Enter',repeat:true,bubbles:true})));assert.equal((await page.evaluate(()=>window.adsFlight.getState())).storyParagraph,1);await page.keyboard.press('Enter');await page.setViewportSize({width:390,height:844})}
  else if(i===1){const layout=await page.evaluate(()=>{const body=document.querySelector('.intro-body');body.scrollTop=body.scrollHeight;const p=document.querySelector('[data-intro-paragraph]:not([hidden])').getBoundingClientRect(),button=document.querySelector('#introContinue').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,textVisible:p.bottom<=button.top,buttonVisible:button.bottom<=innerHeight}});assert.deepEqual(layout,{overflow:false,textVisible:true,buttonVisible:true});await page.screenshot({path:'/tmp/ads-'+engine+'-popup-mobile.png'});await page.locator('#introClose').click()}
  else if(i===2)await page.keyboard.press('Enter');else if(i===3){await page.emulateMedia({reducedMotion:'reduce'});await page.keyboard.press('Escape')}else {assert.equal(await page.locator('#introContinue').textContent(),'BEGIN FLIGHT →');await page.locator('#introClose').click()}
 }
 await page.waitForFunction(()=>window.adsFlight.getState().properTime>0);assert.equal(await page.locator('#introScreen').isVisible(),false);assert.equal(await page.locator('#app').evaluate(e=>e.inert),false);assert.equal(await page.evaluate(()=>document.activeElement.id),'space');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).shipColor,'#ff984f');assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,engine,paragraphs:5,popupOverlay:true,keyboardAndClose:true,mobileReadable:true,date:'2126 AD',errors}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
