const assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const engine=process.argv[2]||'chromium';
(async()=>{const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true,env:{...process.env,PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS:'1',LIBGL_ALWAYS_SOFTWARE:'1'}}:{executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const errors=[];try{
 const page=await browser.newPage({viewport:{width:1100,height:800}});page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/game.js?*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+`
 flightProgram.nextOffer=()=>null;const reviewExtension=gl.getExtension('WEBGL_lose_context');window.__review={
  lose(){reviewExtension.loseContext()},restore(){reviewExtension.restoreContext()},
  mapStrokes(){let count=0;drawMap(new Proxy({}, {get:(o,k)=>()=>{if(k==='stroke')count++}}));return count},
  killOrbit(){fleet[0].deathTime=player.t},
  returnPulse(){reset();trafficFire.enabled=false;const b=createLaser(player,[]);b.flashTime=effectTime;beams=[b];while(player.t<3.04)advance(player,.004,0,false,(s,t)=>advanceLasers(beams,t,s));warp=10;dirty=true},
  history(){reset();trafficFire.enabled=false;const live=createLaser(player,[]);live.flashTime=-Infinity;beams=[live,...Array.from({length:100},()=>({...live,impact:{time:0,ship:'OLD TARGET'}}))];return live},
  pulseHistory(){return {total:beams.length,active:beams.filter(b=>!b.impact).length}},
  oldReturningTracer(){reset();trafficFire.enabled=false;const original=createLaser(player,[]);original.flashTime=-Infinity;beams=[original];for(let i=0;i<60;i++){const past=initialPlayer();advance(past,.1+i*.015);const b=createLaser(past,[]);b.flashTime=-Infinity;beams.push(b)}advance(player,3.08);const observer=viewObserver(),X=laserEvent(original,player.t),z=dot(X,observer.F),expected=[width/2+dot(X,observer.R)/z/1.4*height,height/2-dot(X,observer.V)/z/1.4*height],arcs=[],arc=hctx.arc;hctx.arc=function(x,y,...args){arcs.push([x,y]);return arc.call(this,x,y,...args)};try{drawLaserPulses(observer)}finally{hctx.arc=arc}return {visible:arcs.some(p=>Math.hypot(p[0]-expected[0],p[1]-expected[1])<1e-5),heads:arcs.length,expected}}
 };`})});
 await page.goto(process.env.ADS_URL||'http://127.0.0.1:8080/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.adsFlight?.getState().renderer.frames>0);
 await page.locator('#launchSound').focus();await page.keyboard.press('Enter');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).launched,false);assert.equal(await page.locator('#launchSound').getAttribute('aria-pressed'),'false');
 await page.locator('#launchButton').click();for(let i=0;i<5;i++)await page.keyboard.press('Enter');await page.waitForFunction(()=>window.adsFlight.getState().properTime>0);
 const shots=(await page.evaluate(()=>window.adsFlight.getState())).shots;await page.keyboard.press('Control+f');await page.keyboard.press('Escape');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).shots,shots);await page.keyboard.press('Meta+f');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).shots,shots);await page.keyboard.press('Escape');
 await page.locator('#space').focus();await page.keyboard.down('w');await page.waitForFunction(()=>window.adsFlight.getState().activeControls.includes('KeyW'));await page.locator('#thrust').focus();assert.deepEqual((await page.evaluate(()=>window.adsFlight.getState())).activeControls,[]);await page.keyboard.up('w');
 await page.evaluate(()=>window.adsFlight.setPause(true));const strokes=await page.evaluate(()=>window.__review.mapStrokes());await page.evaluate(()=>window.__review.killOrbit());assert.equal(await page.evaluate(()=>window.__review.mapStrokes()),strokes-2);await page.evaluate(()=>window.adsFlight.reset());
 if(engine==='chromium'){
  await page.locator('#fullscreenButton').click();await page.waitForFunction(()=>!!document.fullscreenElement);assert.equal(await page.evaluate(()=>document.fullscreenElement.contains(document.getElementById('mapDialog'))),true);await page.keyboard.press('m');assert.equal(await page.locator('#mapDialog').evaluate(e=>e.open),true);await page.keyboard.press('Escape');await page.evaluate(()=>document.exitFullscreen());
 }
 const trace=await page.evaluate(()=>window.__review.oldReturningTracer());assert.equal(trace.visible,true,'Older returning pulse must stay visible among newer shots');assert.ok(trace.heads<=48);await page.evaluate(()=>window.__review.history());await page.waitForFunction(()=>window.__review.pulseHistory().total===9);assert.equal((await page.evaluate(()=>window.__review.pulseHistory())).active,1);await page.evaluate(()=>window.adsFlight.reset());
 await page.locator('#space').focus();await page.keyboard.down('w');await page.waitForFunction(()=>window.adsFlight.getState().activeControls.includes('KeyW'));await page.evaluate(()=>window.__review.lose());await page.waitForFunction(()=>!window.adsFlight.getState().renderer.ready);const tau=(await page.evaluate(()=>window.adsFlight.getState())).properTime;await page.waitForTimeout(180);assert.equal((await page.evaluate(()=>window.adsFlight.getState())).properTime,tau);assert.equal(await page.evaluate(()=>window.adsFlight.fire()),false);assert.deepEqual((await page.evaluate(()=>window.adsFlight.getState())).activeControls,[]);await page.keyboard.up('w');await page.evaluate(()=>window.__review.restore());await page.waitForFunction(()=>window.adsFlight.getState().renderer.ready);await page.waitForFunction(t=>window.adsFlight.getState().properTime>t,tau);assert.deepEqual((await page.evaluate(()=>window.adsFlight.getState())).activeControls,[]);
 await page.evaluate(()=>window.__review.returnPulse());await page.waitForFunction(()=>window.adsFlight.getState().gameOver);const dead=await page.evaluate(()=>window.adsFlight.getState());assert.equal(dead.globalTime,dead.latestBeam.impact.time);await page.keyboard.press('m');await page.keyboard.press('Enter');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).gameOver,true);await page.keyboard.press('Escape');await page.keyboard.press('r');assert.equal((await page.evaluate(()=>window.adsFlight.getState())).gameOver,false);assert.equal(await page.evaluate(()=>document.activeElement.id),'space');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({pass:true,engine,fullscreenDialogs:engine==='chromium',oldReturningTracer:trace,keyboard:true,deadOrbits:true,contextRecovery:true,exactFatalTime:true,boundedAbsorbedHistory:true,errors}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
