const assert=require('node:assert/strict');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const engine=process.argv[2]||'chromium';
(async()=>{const browser=await(engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:{executablePath:process.env.CHROMIUM_EXECUTABLE,headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});try{
 const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/game.js?*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+`
 window.__trafficQa={colors(){setPause(true);reset();setPause(true);const source={id:'COLOR TEST',A:player.X,B:player.U,C:[player.R,player.V,player.F],kind:0,size:.8},green=createLaser(player,[],player.F,source);green.flashTime=-Infinity;advance(player,.12);beams=[green];draw(false);const pixels=hctx.getImageData(0,0,hud.width,hud.height).data;let greenPixels=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i+1]>100&&pixels[i+1]>pixels[i]*1.3&&pixels[i+1]>pixels[i+2]*1.15&&pixels[i+3]>25)greenPixels++;mctx.strokeStyle='#50ffa599';const greenStyle=mctx.strokeStyle,strokes=[],stroke=mctx.stroke;mctx.stroke=function(){strokes.push(this.strokeStyle);return stroke.call(this)};try{drawMap()}finally{mctx.stroke=stroke}return {greenPixels,greenMap:strokes.includes(greenStyle),playerBeam:latestPlayerBeam(),scanlines:getComputedStyle(canvas.parentElement,'::after').backgroundImage}}};`})});
 await page.goto(process.env.ADS_URL||'http://127.0.0.1:8081/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.adsFlight?.getState().renderer.frames>0);await page.locator('#launchSound').click();await page.locator('#launchButton').click();for(let i=0;i<5;i++)await page.keyboard.press('Enter');await page.selectOption('#warp','20');await page.waitForFunction(()=>window.adsFlight.getState().trafficShots>=5);await page.evaluate(()=>window.adsFlight.setPause(true));const state=await page.evaluate(()=>window.adsFlight.getState());assert.equal(state.shots,0);assert.equal(state.kills,0);assert.equal(state.armedShips,10);assert.equal(await page.locator('#laserStatus').textContent(),'LASER READY');await page.waitForTimeout(150);assert.equal((await page.evaluate(()=>window.adsFlight.getState())).trafficShots,state.trafficShots);
 const colors=await page.evaluate(()=>window.__trafficQa.colors());assert.ok(colors.greenPixels>100,JSON.stringify(colors));assert.equal(colors.greenMap,true);assert.equal(colors.playerBeam,null);assert.match(colors.scanlines,/repeating-linear-gradient/);await page.screenshot({path:'/tmp/ads-v11-'+engine+'.png'});await page.evaluate(()=>window.adsFlight.reset());const reset=await page.evaluate(()=>window.adsFlight.getState());assert.equal(reset.trafficShots,0);assert.equal(reset.aliveShips,72);assert.equal(reset.shots,0);assert.deepEqual(errors,[]);console.log(JSON.stringify({pass:true,engine,automaticTrafficShots:state.trafficShots,colors,reset:true,errors}));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
